/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/catkin_ws/src/au_uav_ros/srv/Ack.srv
 *
 */


#ifndef AU_UAV_ROS_MESSAGE_ACKREQUEST_H
#define AU_UAV_ROS_MESSAGE_ACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace au_uav_ros
{
template <class ContainerAllocator>
struct AckRequest_
{
  typedef AckRequest_<ContainerAllocator> Type;

  AckRequest_()
    : planeID(0)
    , msgID(0)
    , param_value(0)  {
    }
  AckRequest_(const ContainerAllocator& _alloc)
    : planeID(0)
    , msgID(0)
    , param_value(0)  {
    }



   typedef int16_t _planeID_type;
  _planeID_type planeID;

   typedef int16_t _msgID_type;
  _msgID_type msgID;

   typedef int16_t _param_value_type;
  _param_value_type param_value;




  typedef boost::shared_ptr< ::au_uav_ros::AckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::au_uav_ros::AckRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct AckRequest_

typedef ::au_uav_ros::AckRequest_<std::allocator<void> > AckRequest;

typedef boost::shared_ptr< ::au_uav_ros::AckRequest > AckRequestPtr;
typedef boost::shared_ptr< ::au_uav_ros::AckRequest const> AckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::au_uav_ros::AckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::au_uav_ros::AckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace au_uav_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'au_uav_ros': ['/home/viki/catkin_ws/src/au_uav_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::au_uav_ros::AckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::au_uav_ros::AckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::au_uav_ros::AckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::au_uav_ros::AckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::au_uav_ros::AckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::au_uav_ros::AckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::au_uav_ros::AckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d95a447a727bc97dc8f1fa2e0ae843fc";
  }

  static const char* value(const ::au_uav_ros::AckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd95a447a727bc97dULL;
  static const uint64_t static_value2 = 0xc8f1fa2e0ae843fcULL;
};

template<class ContainerAllocator>
struct DataType< ::au_uav_ros::AckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "au_uav_ros/AckRequest";
  }

  static const char* value(const ::au_uav_ros::AckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::au_uav_ros::AckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 planeID\n\
int16 msgID\n\
int16 param_value\n\
\n\
";
  }

  static const char* value(const ::au_uav_ros::AckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::au_uav_ros::AckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.planeID);
      stream.next(m.msgID);
      stream.next(m.param_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::au_uav_ros::AckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::au_uav_ros::AckRequest_<ContainerAllocator>& v)
  {
    s << indent << "planeID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.planeID);
    s << indent << "msgID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.msgID);
    s << indent << "param_value: ";
    Printer<int16_t>::stream(s, indent + "  ", v.param_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AU_UAV_ROS_MESSAGE_ACKREQUEST_H
