/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/catkin_ws/src/au_uav_ros/srv/SimPlane.srv
 *
 */


#ifndef AU_UAV_ROS_MESSAGE_SIMPLANEREQUEST_H
#define AU_UAV_ROS_MESSAGE_SIMPLANEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace au_uav_ros
{
template <class ContainerAllocator>
struct SimPlaneRequest_
{
  typedef SimPlaneRequest_<ContainerAllocator> Type;

  SimPlaneRequest_()
    : clear(false)
    , planeID(0)
    , add(false)
    , latitudes()
    , longitudes()
    , altitudes()
    , size(0)  {
    }
  SimPlaneRequest_(const ContainerAllocator& _alloc)
    : clear(false)
    , planeID(0)
    , add(false)
    , latitudes(_alloc)
    , longitudes(_alloc)
    , altitudes(_alloc)
    , size(0)  {
    }



   typedef uint8_t _clear_type;
  _clear_type clear;

   typedef int16_t _planeID_type;
  _planeID_type planeID;

   typedef uint8_t _add_type;
  _add_type add;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _latitudes_type;
  _latitudes_type latitudes;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _longitudes_type;
  _longitudes_type longitudes;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _altitudes_type;
  _altitudes_type altitudes;

   typedef int32_t _size_type;
  _size_type size;




  typedef boost::shared_ptr< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SimPlaneRequest_

typedef ::au_uav_ros::SimPlaneRequest_<std::allocator<void> > SimPlaneRequest;

typedef boost::shared_ptr< ::au_uav_ros::SimPlaneRequest > SimPlaneRequestPtr;
typedef boost::shared_ptr< ::au_uav_ros::SimPlaneRequest const> SimPlaneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace au_uav_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'au_uav_ros': ['/home/viki/catkin_ws/src/au_uav_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e400108a855ff68f697fe3694dccfba";
  }

  static const char* value(const ::au_uav_ros::SimPlaneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e400108a855ff68ULL;
  static const uint64_t static_value2 = 0xf697fe3694dccfbaULL;
};

template<class ContainerAllocator>
struct DataType< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "au_uav_ros/SimPlaneRequest";
  }

  static const char* value(const ::au_uav_ros::SimPlaneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool clear\n\
int16 planeID\n\
bool add\n\
float64[] latitudes\n\
float64[] longitudes\n\
float64[] altitudes\n\
int32 size\n\
";
  }

  static const char* value(const ::au_uav_ros::SimPlaneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clear);
      stream.next(m.planeID);
      stream.next(m.add);
      stream.next(m.latitudes);
      stream.next(m.longitudes);
      stream.next(m.altitudes);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SimPlaneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::au_uav_ros::SimPlaneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::au_uav_ros::SimPlaneRequest_<ContainerAllocator>& v)
  {
    s << indent << "clear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear);
    s << indent << "planeID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.planeID);
    s << indent << "add: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.add);
    s << indent << "latitudes[]" << std::endl;
    for (size_t i = 0; i < v.latitudes.size(); ++i)
    {
      s << indent << "  latitudes[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.latitudes[i]);
    }
    s << indent << "longitudes[]" << std::endl;
    for (size_t i = 0; i < v.longitudes.size(); ++i)
    {
      s << indent << "  longitudes[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.longitudes[i]);
    }
    s << indent << "altitudes[]" << std::endl;
    for (size_t i = 0; i < v.altitudes.size(); ++i)
    {
      s << indent << "  altitudes[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.altitudes[i]);
    }
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AU_UAV_ROS_MESSAGE_SIMPLANEREQUEST_H
