/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/catkin_ws/src/au_uav_ros/msg/Telemetry.msg
 *
 */


#ifndef AU_UAV_ROS_MESSAGE_TELEMETRY_H
#define AU_UAV_ROS_MESSAGE_TELEMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace au_uav_ros
{
template <class ContainerAllocator>
struct Telemetry_
{
  typedef Telemetry_<ContainerAllocator> Type;

  Telemetry_()
    : telemetryHeader()
    , planeID(0)
    , currentLatitude(0.0)
    , currentLongitude(0.0)
    , currentAltitude(0.0)
    , destLatitude(0.0)
    , destLongitude(0.0)
    , destAltitude(0.0)
    , groundSpeed(0.0)
    , airSpeed(0.0)
    , targetBearing(0.0)
    , currentWaypointIndex(0)
    , distanceToDestination(0.0)  {
    }
  Telemetry_(const ContainerAllocator& _alloc)
    : telemetryHeader(_alloc)
    , planeID(0)
    , currentLatitude(0.0)
    , currentLongitude(0.0)
    , currentAltitude(0.0)
    , destLatitude(0.0)
    , destLongitude(0.0)
    , destAltitude(0.0)
    , groundSpeed(0.0)
    , airSpeed(0.0)
    , targetBearing(0.0)
    , currentWaypointIndex(0)
    , distanceToDestination(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _telemetryHeader_type;
  _telemetryHeader_type telemetryHeader;

   typedef int32_t _planeID_type;
  _planeID_type planeID;

   typedef double _currentLatitude_type;
  _currentLatitude_type currentLatitude;

   typedef double _currentLongitude_type;
  _currentLongitude_type currentLongitude;

   typedef double _currentAltitude_type;
  _currentAltitude_type currentAltitude;

   typedef double _destLatitude_type;
  _destLatitude_type destLatitude;

   typedef double _destLongitude_type;
  _destLongitude_type destLongitude;

   typedef double _destAltitude_type;
  _destAltitude_type destAltitude;

   typedef double _groundSpeed_type;
  _groundSpeed_type groundSpeed;

   typedef double _airSpeed_type;
  _airSpeed_type airSpeed;

   typedef double _targetBearing_type;
  _targetBearing_type targetBearing;

   typedef int64_t _currentWaypointIndex_type;
  _currentWaypointIndex_type currentWaypointIndex;

   typedef double _distanceToDestination_type;
  _distanceToDestination_type distanceToDestination;




  typedef boost::shared_ptr< ::au_uav_ros::Telemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::au_uav_ros::Telemetry_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Telemetry_

typedef ::au_uav_ros::Telemetry_<std::allocator<void> > Telemetry;

typedef boost::shared_ptr< ::au_uav_ros::Telemetry > TelemetryPtr;
typedef boost::shared_ptr< ::au_uav_ros::Telemetry const> TelemetryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::au_uav_ros::Telemetry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::au_uav_ros::Telemetry_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace au_uav_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'au_uav_ros': ['/home/viki/catkin_ws/src/au_uav_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::au_uav_ros::Telemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::au_uav_ros::Telemetry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::au_uav_ros::Telemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::au_uav_ros::Telemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::au_uav_ros::Telemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::au_uav_ros::Telemetry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::au_uav_ros::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed327d31082684850bc15716fdc27fdf";
  }

  static const char* value(const ::au_uav_ros::Telemetry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed327d3108268485ULL;
  static const uint64_t static_value2 = 0x0bc15716fdc27fdfULL;
};

template<class ContainerAllocator>
struct DataType< ::au_uav_ros::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "au_uav_ros/Telemetry";
  }

  static const char* value(const ::au_uav_ros::Telemetry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::au_uav_ros::Telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header telemetryHeader\n\
int32 planeID\n\
float64 currentLatitude\n\
float64 currentLongitude\n\
float64 currentAltitude\n\
float64 destLatitude\n\
float64 destLongitude\n\
float64 destAltitude\n\
float64 groundSpeed\n\
float64 airSpeed\n\
float64 targetBearing\n\
int64 currentWaypointIndex\n\
float64 distanceToDestination\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::au_uav_ros::Telemetry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::au_uav_ros::Telemetry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.telemetryHeader);
      stream.next(m.planeID);
      stream.next(m.currentLatitude);
      stream.next(m.currentLongitude);
      stream.next(m.currentAltitude);
      stream.next(m.destLatitude);
      stream.next(m.destLongitude);
      stream.next(m.destAltitude);
      stream.next(m.groundSpeed);
      stream.next(m.airSpeed);
      stream.next(m.targetBearing);
      stream.next(m.currentWaypointIndex);
      stream.next(m.distanceToDestination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Telemetry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::au_uav_ros::Telemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::au_uav_ros::Telemetry_<ContainerAllocator>& v)
  {
    s << indent << "telemetryHeader: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.telemetryHeader);
    s << indent << "planeID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.planeID);
    s << indent << "currentLatitude: ";
    Printer<double>::stream(s, indent + "  ", v.currentLatitude);
    s << indent << "currentLongitude: ";
    Printer<double>::stream(s, indent + "  ", v.currentLongitude);
    s << indent << "currentAltitude: ";
    Printer<double>::stream(s, indent + "  ", v.currentAltitude);
    s << indent << "destLatitude: ";
    Printer<double>::stream(s, indent + "  ", v.destLatitude);
    s << indent << "destLongitude: ";
    Printer<double>::stream(s, indent + "  ", v.destLongitude);
    s << indent << "destAltitude: ";
    Printer<double>::stream(s, indent + "  ", v.destAltitude);
    s << indent << "groundSpeed: ";
    Printer<double>::stream(s, indent + "  ", v.groundSpeed);
    s << indent << "airSpeed: ";
    Printer<double>::stream(s, indent + "  ", v.airSpeed);
    s << indent << "targetBearing: ";
    Printer<double>::stream(s, indent + "  ", v.targetBearing);
    s << indent << "currentWaypointIndex: ";
    Printer<int64_t>::stream(s, indent + "  ", v.currentWaypointIndex);
    s << indent << "distanceToDestination: ";
    Printer<double>::stream(s, indent + "  ", v.distanceToDestination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AU_UAV_ROS_MESSAGE_TELEMETRY_H
