(cl:in-package au_uav_ros-msg)
(cl:export '(TELEMETRYHEADER-VAL
          TELEMETRYHEADER
          PLANEID-VAL
          PLANEID
          CURRENTLATITUDE-VAL
          CURRENTLATITUDE
          CURRENTLONGITUDE-VAL
          CURRENTLONGITUDE
          CURRENTALTITUDE-VAL
          CURRENTALTITUDE
          DESTLATITUDE-VAL
          DESTLATITUDE
          DESTLONGITUDE-VAL
          DESTLONGITUDE
          DESTALTITUDE-VAL
          DESTALTITUDE
          GROUNDSPEED-VAL
          GROUNDSPEED
          AIRSPEED-VAL
          AIRSPEED
          TARGETBEARING-VAL
          TARGETBEARING
          CURRENTWAYPOINTINDEX-VAL
          CURRENTWAYPOINTINDEX
          DISTANCETODESTINATION-VAL
          DISTANCETODESTINATION
))